<?xml version="1.0" encoding="utf-8"?><Database Name="QLDuLich" Class="AddminTourDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-0RP6AU8\SQLEXPRESS;Initial Catalog=QLDuLich;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QLDuLichConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tour" Member="Tours">
    <Type Name="Tour">
      <Column Name="IdTour" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTour" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HanhTrinh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoNgay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaDiLai" Type="System.Double" DbType="Money" CanBeNull="true" />
      <Column Name="GiaPhong" Type="System.Double" DbType="Money" CanBeNull="true" />
      <Column Name="ThongTin" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NgayDi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayVe" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Tour_Customer" Member="Customers" ThisKey="IdTour" OtherKey="MaTour" Type="Customer" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Idcustomer" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TenCustomer" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TuoiCustomer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaTour" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Tour_Customer" Member="Tour" ThisKey="MaTour" OtherKey="IdTour" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
</Database>